/**
 * Builds the bundled hymn corpus from the authoring files in content/.
 *
 * Run with: npm run build:corpus
 *
 * Inputs   content/*.json  — each file holds { hymns: Hymn[] }
 * Outputs  assets/hymns/index.json     light summaries for lists/grouping
 *          assets/hymns/full/NNN.json  chunks of full records, lazily loaded
 *          src/data/generated-chunks.ts  static require() map (see below)
 *
 * Metro resolves `require()` arguments at build time, so a dynamically
 * constructed path like `require('./full/' + id + '.json')` fails at runtime.
 * The generated module therefore lists every chunk as a literal require, and
 * must be regenerated whenever the corpus changes.
 */
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { validateCorpus, formatIssues } from './lib/validate.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT_DIR = join(ROOT, 'content');
const ASSET_DIR = join(ROOT, 'assets', 'hymns');
const FULL_DIR = join(ASSET_DIR, 'full');
const CHUNKS_FILE = join(ROOT, 'src', 'data', 'generated-chunks.ts');

/** Hymns per chunk. 100 keeps each file ~400 KB, so search loads ~5 MB total. */
const CHUNK_SIZE = 100;

/** Stable id from the hymn number, zero-padded so ids sort naturally. */
const idFor = (number) => `h${String(number).padStart(4, '0')}`;

async function readContent() {
  const entries = (await readdir(CONTENT_DIR))
    .filter((name) => name.endsWith('.json'))
    .sort();

  if (entries.length === 0) throw new Error(`no .json files in ${CONTENT_DIR}`);

  const hymns = [];
  for (const name of entries) {
    const raw = JSON.parse(await readFile(join(CONTENT_DIR, name), 'utf8'));
    const list = Array.isArray(raw) ? raw : raw.hymns;
    if (!Array.isArray(list)) throw new Error(`${name}: expected an array or { hymns: [] }`);
    hymns.push(...list);
  }
  return hymns;
}

function toSummary(hymn) {
  return {
    id: hymn.id ?? idFor(hymn.number),
    number: hymn.number,
    title: hymn.title,
    meter: hymn.meter,
    hasChorus: (hymn.verses ?? []).some((v) => v.chorus),
  };
}

function generateChunksModule(chunks) {
  const entries = chunks
    .map((chunk) => `  ${chunk.index}: require('../../assets/hymns/full/${chunk.file}') as Hymn[],`)
    .join('\n');

  return `// AUTO-GENERATED by scripts/build-corpus.mjs — do not edit by hand.
// Run \`npm run build:corpus\` after changing anything in content/.

import type { Hymn } from './types';

/** Full hymn records, chunked. ${chunks.length} chunk(s) of up to ${CHUNK_SIZE}. */
export const HYMN_CHUNKS: Record<number, Hymn[]> = {
${entries}
};

export const HYMN_CHUNK_COUNT = ${chunks.length};
`;
}

async function main() {
  const raw = await readContent();

  const issues = validateCorpus(raw);
  if (issues.length > 0) {
    console.error(`corpus validation failed (${issues.length} issue(s)):\n${formatIssues(issues)}`);
    process.exit(1);
  }

  // Normalise: assign ids, sort by hymn number, and default the chorus flags.
  const hymns = raw
    .map((hymn) => ({
      ...hymn,
      id: hymn.id ?? idFor(hymn.number),
      verses: (hymn.verses ?? []).map((verse) => ({
        ...verse,
        chorus: verse.chorus ?? false,
      })),
    }))
    .sort((a, b) => a.number - b.number);

  const duplicates = hymns
    .map((h) => h.id)
    .filter((id, i, all) => all.indexOf(id) !== i);
  if (duplicates.length > 0) {
    console.error(`duplicate ids: ${[...new Set(duplicates)].join(', ')}`);
    process.exit(1);
  }

  await rm(ASSET_DIR, { recursive: true, force: true });
  await mkdir(FULL_DIR, { recursive: true });

  const summaries = hymns.map(toSummary);
  await writeFile(join(ASSET_DIR, 'index.json'), JSON.stringify(summaries, null, 1) + '\n');

  const chunks = [];
  for (let i = 0; i < hymns.length; i += CHUNK_SIZE) {
    const index = chunks.length;
    const file = `${String(index).padStart(3, '0')}.json`;
    await writeFile(join(FULL_DIR, file), JSON.stringify(hymns.slice(i, i + CHUNK_SIZE)) + '\n');
    chunks.push({ index, file });
  }

  await writeFile(CHUNKS_FILE, generateChunksModule(chunks));

  const bytes = summaries.length === 0 ? 0 : JSON.stringify(hymns).length;
  console.log(
    `${hymns.length} hymns -> ${chunks.length} chunk(s), ` +
      `index ${(JSON.stringify(summaries).length / 1024).toFixed(0)} KB, ` +
      `full ~${(bytes / 1024 / 1024).toFixed(2)} MB`,
  );
  console.log('wrote assets/hymns/ and src/data/generated-chunks.ts');
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
