// AUTO-GENERATED by scripts/build-corpus.mjs — do not edit by hand.
// Run `npm run build:corpus` after changing anything in content/.

import type { Hymn } from './types';

/** Full hymn records, chunked. 1 chunk(s) of up to 100. */
export const HYMN_CHUNKS: Record<number, Hymn[]> = {
  0: require('../../assets/hymns/full/000.json') as Hymn[],
};

export const HYMN_CHUNK_COUNT = 1;
